backend = "egl";
vsync = true;
use-damage = true;

# shadows
shadow = true;
shadow-radius = 10;
shadow-opacity = 0.8;
shadow-offset-x = -7;
shadow-offset-y = -7;

# fading / animations
fading = true;
fade-in-step = 0.1;
fade-out-step = 0.1;
fade-delta = 5;
no-fading-openclose = false;

# rounded corners
corner-radius = 12;
rounded-corners-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];

# opacity
inactive-opacity = 0.6;
opacity-rule = [
    "100:class_g = 'Rofi'"
];

# blur
blur: {
    method = "dual_kawase";
    strength = 6;
};

blur-background = true;
blur-background-frame = true;
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'",
    "class_g = 'maim'",
    "class_g = 'slop'"
];

detect-rounded-corners = true;
detect-client-opacity = true;

wintypes:
{
    dock = {
        shadow = false;
        fade = false;
        blur-background = false;
    };

    dropdown_menu = {
        shadow = false;
        fade = false;
        blur-background = false;
    };

    popup_menu = {
        shadow = false;
        fade = false;
        blur-background = false;
        opacity = 1.0;
    };

    tooltip = {
        shadow = false;
        fade = false;
        blur-background = false;
        opacity = 1.0;
    };

    utility = {
        shadow = false;
        fade = false;
        blur-background = false;
        opacity = 1.0;
    };
};
