#!/bin/sh

#autostart
pgrep -x sxhkd > /dev/null || sxhkd &
pkill picom
picom --experimental-backends &
feh --bg-fill ~/Pictures/wallpapers/dreams.jpg
~/.config/polybar/launch.sh &
# set default cursor state
xsetroot -cursor_name left_ptr &

#monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#window information
bspc config window_gap 9
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

# Border width
bspc config border_width 2

# Active / inactive colors (subtle gray shades)
bspc config focused_border_color "#999999"
bspc config normal_border_color  "#666666"

# Optional: remove preselection border if visible
bspc config presel_feedback_color "#3a3a3a"

#rules
bspc rule -a mumble state=floating follow=on focus=on

