;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[global/wm]
margin-top    = 2
margin-bottom = 0
include-file  = ~/.config/polybar/colors.ini
include-file  = ~/.config/polybar/modules.ini


[bar/main]
width  = 99%
height = 24
offset-x = 0.5%
offset-y = 6
radius = 8.0
bottom = false
fixed-center = true

background = #00000000
foreground = #d0d0d0

line-size  = 0

; thin subtle border in dark gray
border-size  = 0
border-color = #2a2a2a

padding-left  = 0
padding-right = 0

module-margin-left  = 0
module-margin-right = 0

font-0 = FiraCode Nerd Font:style=Medium:size=9;2

modules-left   = bspwm
modules-center = date
modules-right  = ind-weather weather gap ind-system system_pill gap ind-status status_pill

wm-restack = bspwm
enable-ipc = true

[settings]
screenchange-reload = true
